config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"
  get 'about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  
end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user

	#dependent: :destroy  deletes nest controllers
	has_many 	:comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment, only: [:create, :destroy]
	before_action :comment_auth, only: [:destroy]


	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id]).destroy
		redirect_to post_path(@post)
	end

	private

	def comment_params
		params.require(:comment).permit(:name, :body)
	end

	def find_comment
		@post = Post.find(params[:post_id])
	end

	def comment_auth
		if current_user != @post.user
		redirect_to(root_path)
		end
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]	
before_action :authenticate_user!, except: [:index, :show]
before_action :post_auth, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		#@post = Post.new
		@post = current_user.posts.build
	end

	def create
		@post = Post.new(post_params)
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def find_post
		@post = Post.find(params[:id])
	end

	# Checks if current user authored pin      
	def post_auth
		if current_user != @post.user
		redirect_to(root_path)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .comment_content
    %p.comment_name
      %strong= comment.name
    %p.comment_body= comment.body
    %p.comment_time
      = time_ago_in_words(comment.created_at)
      Ago
  - if comment.user == current_user
    %p= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|
  = f.label :name
  %br
    = f.text_field :name
    %br
      %br
        = f.label :body
        %br
          = f.text_area :body
          %br
            %br
              = f.submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Blog
	= stylesheet_link_tag 		'application', media: 'all', 'data-turbolinks-track' => true
	= stylesheet_link_tag 		'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700'
	= javascript_include_tag  'application', 'data-turbolinks-track' => true
	= favicon_link_tag 'favicon.ico'
	= csrf_meta_tags

%body
	#sidebar
		#logo
			=link_to root_path do
				=image_tag "logo.svg"
		%ul
			%li.category Website
			%li= link_to "Blog", root_path
			%li= link_to "About", about_path

		%ul
			%li.category Social
			%li= link_to "Facebook", "http://facebook.com"
			%li= link_to "Twitter", "http://twitter.com"
		
		-if !user_signed_in?
			%p.sign_in
				= link_to "Admin Login", new_user_session_path
	
	#main_content
		#header
			- if current_page?(root_path)
				%p All Posts
			- elsif current_page?(about_path)
				%p About
			- else
				= link_to "Back to All Posts", root_path
				
			-if user_signed_in?
				.buttons
					.button.button= link_to 'New Post', new_post_path
					.button.button= link_to 'Log Out', destroy_user_session_path, method: :delete

		-flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"
		= yield

app/views/pages/about.html.haml
#page_wrapper
  #profile_image
    = image_tag "profile.jpeg"
  #content
    %h1 Hey, I'm Mackenzie Child
    %p Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.
    %p This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.
    %p
      If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter
      %a{:href => "http://twitter.com/mackenziechild"} @MackenzieChild
      or on the web at
      = succeed "," do
        %a{:href => "http://mackenziechild.me"} mackenziechild.me
      and get my posts and exclusive content in your inbox by signing up for my newsletter
      = succeed "." do
        %a{:href => "http://eepurl.com/02olT"} here

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #errors
      %h2
        = pluralize(@post.errors.count, "error")
        prevented this post from saving:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  = f.label :title
  %br
    = f.text_field :title
    %br
      %br
        = f.label :body
        %br
          = f.text_area :body
          %br
            %br
              = f.submit

app/views/posts/edit.html.haml
#page_wrapper
	%h1 Edit Post
	=render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
	.post_wrapper
		%h2.title= link_to post.title, post
		%p
			= pluralize( post.comments.count, "Comments" )
		%p.date= post.created_at.strftime("%B %-d, %Y")
		

app/views/posts/new.html.haml
#page_wrapper
	%h1 New Post
	=render 'form'

app/views/posts/show.html.haml
#post_content
	%h1.title= @post.title

	%p.date
		= "Submitted #{time_ago_in_words(@post.created_at)} Ago"
	%p.body= @post.body
	%p= @post.user.email
	-if @post.user == current_user
		=link_to 'Edit', edit_post_path(@post)
		|
		=link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}

	#comments
		%h2
			= pluralize( @post.comments.count, "Comment" )
			= render @post.comments
		
		-if user_signed_in?
			%h3 
				Add Comment:

			%p
				= render "comments/form"